---
exclude: ["README.markdown"]
permalink: ":title"
safe: false
title: "insane.works"
author: "@insanj"
description: "ğŸ› creative works by julian weiss"
description_biline: "ğŸ‘¾ Â© 2022"
highlighter: rouge
