---
exclude: ["README.markdown"]
permalink: ":title"
safe: false
title: "julian.coffee"
author: "@insanj"
description: "ğŸ› creative works by julian weiss"
description_biline: "â¤ made with love<div></div>Â© 2018-2024"
highlighter: rouge
